### ISSUE TITLE
Add support for google profile pictures

### ISSUE THREAD

**Issue by rogeredthat** [crux-bphc/fest-manager#13]
1. At time of authentication, store `url` of display picture from the profile object returned by google in database (Requires changes to `authentication.js` and `users.model.js`)
2. Add an else case before the fallback in `index.jade`.

**Comment by praneetmehta** [comment]
Hey. I am on it.

**Comment by praneetmehta** [comment]
will it better if we prioritize google or facebook images over github, i mean move googleID to the if statement instead of github?

**Comment by praneetmehta** [comment]
will it be better if we prioritize google profile images instead of github. I mean checking of googleID first then facebook and then github in index.jade?

**Comment by aero31aero** [comment]
@praneetmehta That'd be fine. I kept google at last because we didn't have those images then. Resolving this issue means we can keep google anf facebook on top.

**Comment by rogeredthat** [comment]
There's one more thing. `authentication.js` has a block which fixes info of users who were registered before the given feature was added. We need an extra block that rechecks the profile picture. Or instead we could have a refactor that would hold an array of all fields that need a check. All fields, will have a corresponding function called before `user.save(...)` instead of the regular assignment of properties and also if an existing user is missing the field.

**Comment by aero31aero** [comment]
I'll generalize this soon. marking it as defer.

**Comment by rogeredthat** [comment]
Update: New registrations are picking up the updated image url. Migration of previously registered users remains.

**Comment by rogeredthat** [comment]
Update: https://github.com/crux-bphc/fest-manager/commit/88f58034e6da2c534a4e70e083ab4a648ec815bf fixes the issue. We are modifying the url on the fly and not migrating the past databases.
