### ISSUE TITLE
bug: UI element overlap in account display

### ISSUE THREAD

**Issue by Nischay-Pro** [crux-bphc/fest-manager#135]
![image](https://user-images.githubusercontent.com/15060256/28493230-88662270-6f30-11e7-96e6-c12ebfa55a7d.png)

Campus Ambassador overlaps the user name

**Comment by rogeredthat** [comment]
@tanmaychandekar98 please look into this. Will require wrapping the name.

**Comment by aero31aero** [comment]
Closing as dormant and there have been significant changes to the page to render this bug report as useful now.
