### ISSUE TITLE
₹ symbol not showing properly in events

### ISSUE THREAD

**Issue by Jain-Samkit** [crux-bphc/fest-manager#195]
₹ symbol is shown as superscript on each event page where prize money is mentioned
![capture](https://user-images.githubusercontent.com/15244493/30188881-9b122b9c-944e-11e7-8b6a-bfaac91133df.JPG)

**Comment by rogeredthat** [comment]
A surprising number of people like to do this. I'm not alone :stuck_out_tongue: Google: **price design**
<img src="https://i.pinimg.com/736x/2f/7e/19/2f7e19bfb1024db104d744cf211b9577--dashboard-ui-ui-ux.jpg" width=400 /> 
<img src="https://cdn.dribbble.com/users/472528/screenshots/2120360/material-design-pricing-table_1x.png" width=400 />

**Comment by sharath-golluri97** [comment]
Please reconsider this design and take the opinion of the majority here. People feel that the larger version would be better aesthetically.

**Comment by aero31aero** [comment]
Closing as a design decision that wouldn't be overturned.
