### ISSUE TITLE
Open in new tab not available

### ISSUE THREAD

**Issue by rogeredthat** [crux-bphc/fest-manager#199]
Because of the way we are managing navigation, it has become impossible to open a link in a new tab. Some sort of refactor would be required. The `_route` attribute could become href again and maybe everything should be replaced back as an anchor. Then using `preventDefault` with the `onclick` on these tags could do the deal.

**Comment by rogeredthat** [comment]
I wrote a short [pen](https://codepen.io/calvrix/pen/GvLMNd) demonstrating the functionality. Should be an easy implementation beyond this.

**Comment by aero31aero** [comment]
Assigned to @anspd with a deadline of Sept 26 to production.
