### ISSUE TITLE
404: 404 page not found

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/fest-manager#211]
Create a decent 404 page and render it when needed. Take inspiration from the Work In Progress pages created for PyBits.

**Comment by rogeredthat** [comment]
The fix in https://github.com/crux-bphc/fest-manager/commit/f03079edad03777384a520369c83f7fdd127fa9a created a bug, that was throwing valid routes on the not-found handler.
This can be avoided by handling 404 errors on the front-end. In `public/static/scripts/index.js` watch for a response returning with a 404 status code. Implement the following page: https://codepen.io/rileyjshaw/pen/ufEIH

**Comment by aero31aero** [comment]
Also remove/revert f03079e in your PR.
