### ISSUE TITLE
portals: Set up portals for event population

### ISSUE THREAD

**Issue by aero31aero** [CRUx-BPHC/fest-manager#62]
We have the following tasks to accomplish to close this issue:

- [ ] Generate a generic `form-handler.js` on the frontend to replace the current `register.js` and `newevents.js` files.
- [x] Add CSS for form elements `textarea` and `select`. These should be styled similarly to the `input` elements.
- [ ] Add a datetime picker using JQuery with a simple HTML syntax to `form-handler.js`.
- [ ] Add Jade markup to the `mixins/field.jade` to support this datetime syntax.
- [ ] Extend backend validation logic to allow a user to be in more than one body.
- [ ] Fill the field `body` in the event code in the backend to prevent an attack vector for adding false events.

All these tasks require descriptions onto themselves which I would try to append here. If I haven't added it yet, PM me and I'll communicate the needs precisely to you. :)

If you are taking up a task, comment the task number that you are taking on.

**Comment by rogeredthat** [comment]
I'm doing this one.

**Comment by rogeredthat** [comment]
Why should a user be in more than one body?

**Comment by aero31aero** [comment]
@rogeredthat we need a datetime picker soon. Rest of the events page looks ready. Closing this as the release milestone goals have been reached, and datetime work is for after the initial release.
