### ISSUE TITLE
deployment: Deploy to Digital Ocean

### ISSUE THREAD

**Issue by aero31aero** [CRUx-BPHC/fest-manager#65]
Write a script to deploy to Digital Ocean and set up the environment variables for Production.

Also we need to set up CNAME files and point the bits-atmos.org domain to our Digital Ocean instance.

Task list:
- [ ] Deployment Script
- [x] Redirection Rules
- [x] Https Configuration

**Comment by rogeredthat** [comment]
Proceeded with deploying a droplet on [digital ocean](http://139.59.79.46). Name servers were assigned to the domain bits-atmos.org. DNS propagation will take around 24hrs.
Node, mongodb and the repository were set up and deployed successfully. The concerned people have credentials to the account and can login.

**Comment by Nischay-Pro** [comment]
CNAMEs are done.

**Comment by aero31aero** [comment]
SSL Status?

**Comment by Nischay-Pro** [comment]
Once you approve PR we can test
