### ISSUE TITLE
Close button in immersive mode should go back to previous page

### ISSUE THREAD

**Issue by aero31aero** [CRUx-BPHC/fest-manager#66]
Right now, we redirect to `/dashboard` on pressing the close button in immersive mode. 

We should instead store the URL from which the immersive mode was first triggered and the close button should go back to it. If immersive mode was triggered directly (say, someone directly opened the homepage), the `/about` redirection should take place.

**Comment by rogeredthat** [comment]
I'm doing this. Will be ready with a PR in a while.

**Comment by rogeredthat** [comment]
I think it'd work perfectly in such scenarios.. If the previous state mentions `isImmersive:true`
