### ISSUE TITLE
frontend: Create an About Atmos page.

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/fest-manager#67]
We need to have a page that tells what atmos is (tech fest) which the landing page would not tell and other pages need not even care about.

The page would ideally have a text description with contact information. We could also have an image gallery of sorts here.

Discuss design ideas by commenting on this issue before implementing, and if you want to, just implement a small part of this and leave the other parts to other devs.

The backend route would be `/about` and would need to be written in `routes/components/about.js`.

**Comment by rogeredthat** [comment]
Should we change the CONTACT tab in sidebar to ABOUT, and have it hold the contact, about the fest, gallery and atmos2k16 website?

**Comment by aero31aero** [comment]
Agreed. on that front.

**Comment by aero31aero** [comment]
Update: we now have blank pages for filling the content in. See `views/about/*.jade` files to add content.

**Comment by rogeredthat** [comment]
Update: We now have plain text pages. This issue would be closed once we have better theming.

**Comment by aero31aero** [comment]
Update: @yashdeep97 is working on the map page. The Contacts page is done. This issue is *almost* there.
