### ISSUE TITLE
Figure out an image pipeline

### ISSUE THREAD

**Issue by aero31aero** [CRUx-BPHC/fest-manager#68]
We need to upload event icons and posters, and thus, we need an image uploading, cropping and storage solution.

For each event, we need two images: 
1. Profile Image (square)
2. Hero Image (16:9 landscape)

We need to upload these images on the server and have to consider either of these two storage options:

1. Store as files on server and store that path along with the image. ( I don't like this idea because its more likely to introduce vulnerabilities and also requires 2 reads of the harddisk, one for Mongo and one for image)
2. Store by encoding to base64 in the database itself. ( I don't like this idea because this increases the size of each record in the collection and might make fetching slower. Needs research)

Basically, I don't like either but we'd go with one of them after researching which is less worse than the other.

About uploading, we need a cropping tool (perhaps a jquery plugin, you never run out of those).

**Comment by sohailrajdev97** [comment]
Just a suggestion. Maybe we can save the image with the name `md5(event-id)`. Once that is done, we can directly access the image using the id of the event which is being viewed.

**Comment by rogeredthat** [comment]
Is a good idea. We'll implement this. Also, we're storing the image on the server, increasing the record size is a bad idea. With the image name stored in this manner it'll be a regular fetch of resources to the client side.

**Comment by sohailrajdev97** [comment]
Should I work on that ?

**Comment by aero31aero** [comment]
@sohailrajdev97 Yes. You'd need to coordinate with Abhilash.

Extend the mixins/field.jade with an image chooser and also implement the backend logic to hash them as md5. 

Maybe the images could go to public/data/images/jfs1hdjs.png and this data folder be git ignored.

**Comment by rogeredthat** [comment]
The hashing bit will have to have the client side involved. We cannot get the event ID unless the event has been posted, and the ID retained. An upload method will not be posted along with the rest of the form but instead will have to occur as soon as the image is selected. At this stage, the backend will not know what event context fired the upload. This will have to be sent along, by the client side.
