### ISSUE TITLE
Google profile Images are not stored if user already exists.

### ISSUE THREAD

**Issue by aero31aero** [CRUx-BPHC/fest-manager#76]
## Issue

The code to add google profile images to the database runs only when a user doesn't exist. It should run whenever someone logs in via google.

The code is in `utils/authentication.js`.

```js
if(provider == 'googleID'){
    user.profileImage = profile._json.image.url;
}
```

It currently is in the block `if (!user)`. Add this code just below the corresponding `else` block as well.

## Testing Instructions

1. Run `tools/destroy-and-rebuild-database yourid@gmail.com`.
2. Run `npm start`
3. Try logging in. Your profile pic should be displayed on the top right corner.

![image](https://user-images.githubusercontent.com/8033238/28275029-47649c1a-6b30-11e7-8770-03b9c6c40eef.png)

**Comment by addy007-icy** [comment]
Closing statement:
Done.
