### ISSUE TITLE
events: Rewrite styles for events page

### ISSUE THREAD

**Issue by aero31aero** [CRUx-BPHC/fest-manager#8]
This is a sample event object:

```jade
mixin eventMixin(data)
	div.event-container
		div.image
			img(src="#{data.img}")
		div.details
			div.title-container
				a.title(href="#{data.link}")
					span= data.title
			div.tagline-container
				span.tagline= data.tagline
			div.timestamp-container
				span.timestamp= data.timestamp
			div.category-container
				span.category= data.category
```
The CSS file is `public/stylesheets/events.css`. See the current layout and rewrite it so that it resizes better on mobile.

**Comment by academy-codex** [comment]
I'll redesign the event page to make it responsive and with a better UI.

**Comment by aero31aero** [comment]
Thanks for working on this @academy-codex . :)

Since we load the events from a database and it might be unwieldy to enter dummy events in it, for testing I suppose you could pass dummy objects to the template in `routes/components/events.js`.

If you face any problems, we hang out on tg://join?invite=AAAAAEQ15QsJiYVZ52ekQA to help out.

**Comment by academy-codex** [comment]
Awesome!
I'll get back to guys soon and join the group as well.

Cheers!

**Comment by aero31aero** [comment]
Closing. Superseded by #63 and this part has been completed.
