### ISSUE TITLE
frontend: Fix Github Email is Private Notification Message

### ISSUE THREAD

**Issue by Nischay-Pro** [CRUx-BPHC/fest-manager#99]
Description:
When a user has configured his profile to have his email private the application displays a Github Email is private error message. Fix the error message, since it shows on top of all elements and fix the close button.

Reproduce:
Configure GitHub profile set email to private
Try logging in via Github.
Check

![image](https://user-images.githubusercontent.com/15060256/28359430-c83e73c8-6c8f-11e7-9f7e-bd93b01a2bf6.png)

**Comment by aero31aero** [comment]
Fixing instructions: Add sweet alert library to display such prompts. That library would also be used to display success messages etc where needed. Make sure to get sweet alert 1 and configure it in `public/scripts/index.js`.

**Comment by rogeredthat** [comment]
Fixed by #101
